### ISSUE TITLE
Configuración de permisos en Android 6.0

### ISSUE THREAD

**Issue by impreza233** [Onelio/MyUACloud#10]
Falta el permiso de la superposición de pantalla para API 23 o superior
![imagen](https://cloud.githubusercontent.com/assets/25793051/23095511/3663dfa6-f60b-11e6-82ad-a0457518d854.png)
![imagen](https://cloud.githubusercontent.com/assets/25793051/23095527/83922350-f60b-11e6-86cc-d331d2c092a8.png)

**Comment by Onelio** [comment]
Esto no es un error, es una característica de android

**Comment by Onelio** [comment]
Se ha sustituido la Alerta tardicional para no provocar superposicion de pantalla.
