### ISSUE TITLE
Cambio en la Interfaz de Materiales

### ISSUE THREAD

**Issue by impreza233** [Onelio/MyUACloud#11]
Mi propuesta es cambiar la interfaz de materiales debido a los siguientes motivos: 
**SITUACIÓN ACTUAL**
Un usuario entra a Materiales, y ve únicamente sus materiales pendientes. No sabe que, dándole al botón de materiales, puede cambiar entre uno u otro. 
**PROPUESTA DE SOLUCIÓN**
-Introducción de dos botones, uno para ver los materiales pendientes, y otro para ver todos los materiales, tal y como se comenta en el siguiente esquema. Así, el usuario no estará confundido al entrar a la interfaz. 
![imagen](https://cloud.githubusercontent.com/assets/25793051/23095661/b0164152-f60d-11e6-96af-7644016048a5.png)

**Comment by impreza233** [comment]
Propongo también que en tutorías exista el mismo esquema, tanto para las tutorías leídas como sin leer todavía.

**Comment by Onelio** [comment]
*Cambios atrasados, se tiene pensado añadir interfaz en el Dialog Conjunta.

**Comment by Onelio** [comment]
Se ha añadido un toolbar específico
