### ISSUE TITLE
Problemas de visualización en profesores en Android 4.1-4.3 (API 16-18)

### ISSUE THREAD

**Issue by impreza233** [Onelio/MyUACloud#12]
Cuando voy a ver los profesores, la aplicación da Force Close. Éste es el log
![imagen](https://cloud.githubusercontent.com/assets/25793051/23095685/49fc7d86-f60e-11e6-8f92-bcabd3d3ad45.png)
![imagen](https://cloud.githubusercontent.com/assets/25793051/23095688/4e86ae76-f60e-11e6-835f-d960f6e06835.png)
![imagen](https://cloud.githubusercontent.com/assets/25793051/23095692/550982a0-f60e-11e6-9539-6089bf048197.png)

**Comment by Onelio** [comment]
Fixeado
