### ISSUE TITLE
Problemas de estabilidad moderados

### ISSUE THREAD

**Issue by impreza233** [Onelio/MyUACloud#9]
La aplicación da Forzar Cierre de forma aleatoria ciertas veces, especialmente, cuando el modo de Notificación está activado. No pasa en todas las versiones de Android, sino en unas pocas: 
-Android >6.0: ESTABLE,
-Android 5.0-5.1: ESTABLE
-Android 4.4: ESTABLE
-Android 4.1-4.3: INESTABLE, da Forzar Cierre de forma aleatoria, tanto si están activas las notificaciones como si no.

**Comment by impreza233** [comment]
![captura de pantalla 2017-02-18 a las 19 16 10](https://cloud.githubusercontent.com/assets/25793051/23095708/c640334c-f60e-11e6-9d8b-a8243beb84c9.png)
![captura de pantalla 2017-02-18 a las 19 16 50](https://cloud.githubusercontent.com/assets/25793051/23095711/d1cce246-f60e-11e6-8408-86dfdbf56dd6.png)
![captura de pantalla 2017-02-18 a las 19 17 06](https://cloud.githubusercontent.com/assets/25793051/23095712/db966bf8-f60e-11e6-8301-9fe7e57ead99.png)

**Comment by Onelio** [comment]
El problema es devido a un problema de compatibilidad existente en las versiones anteriores a Kitkat con el formato de texto JSON, concretamente en JSONArray. Pues no existe forma de eliminar un elemento de estos sin el conjunto.
Cerrado, se ha impedido el cierre forzado pero no se puede hacer mucho más por una versión tan antigua y con tantas incompatibilidades.
